version: "3"
services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    stdin_open: true

  redis:
    image: redis
    command: redis-server --port 6379
    restart: always
    ports:
      - 6379:6379

  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  backend:
    depends_on:
      - redis
      - mongo_db
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/src/app

  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3000:80